[package]
name = "aurena"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.46"
crossterm = "0.29.0"
ffmpeg-next = "8.0.0"
image = "0.25.6"
terminal_size = "0.4.3"

[build-dependencies]
cc = "1.0"
bindgen = "0.69"
